version: '3'
services:

  # See https://www.jaegertracing.io/docs/1.33/getting-started/#all-in-one
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      METRICS_STORAGE_TYPE: prometheus
      PROMETHEUS_SERVER_URL: http://prometheus:9090
    ports:
      - "16686:16686" # Web Frontend
      - "14250:14250" # HTTP Accept model.proto
      - "14269:14269" # HTTP Health Check at / and metrics at /metrics

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.53.0
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "4317:4317" # gRPC OTLP receiver
      - "4318:4318" # HTTP OTLP receiver
      - "9411:9411" # Zipkin endpoint
      - "8888:8888" # HTTP Prometheus metrics exposed by the collector
      - "8889:8889" # HTTP Prometheus exporter metrics
      - "13133:13133" # Collector Health Check
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3001:3001"
    depends_on:
      - prometheus

  # Microservice Simulator
#  microsim:
#    image: yurishkuro/microsim:latest
#    command: "-j http://otel-collector:14278/api/traces -d 24h -s 500ms"
#    depends_on:
#      - otel-collector
