version: "2"
services:

  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    environment:
      METRICS_STORAGE_TYPE: prometheus
      PROMETHEUS_SERVER_URL: http://prometheus:9090
    ports:
      - "16686:16686" # HTTP Jaeger UI
      - "14250:14250" # HTTP Accept model.proto
      - "14269:14269" # HTTP Health Check at / and metrics at /metrics

  otel-collector:
    container_name: otel-collector
    image: ${OTELCOL_IMG}
    command:
      [
        "--config=/etc/otel-collector-config.yaml",
        "${OTELCOL_ARGS}"
      ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # gRPC OTLP receiver
      - "4318:4318" # HTTP OTLP receiver
      - "8888:8888" # HTTP Prometheus metrics exposed by the collector
      - "8889:8889" # HTTP Prometheus exporter metrics

    depends_on:
      - jaeger-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
