scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
  - job_name: 'jaeger-all-in-one'
    scrape_interval: 10s
    static_configs:
      - targets: ['jaeger-all-in-one:14269']
