{
 "title": "Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serviceNames",
    "label": "Services",
    "query": {
     "query": "label_values(calls_total, service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name, operation)(rate(calls_total{service_name=~\"$serviceNames\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (service_name, operation)(rate(calls_total{status_code!=\"STATUS_CODE_UNSET\", service_name=~\"$serviceNames\"}[$__rate_interval]))) / on (service_name, operation) (sum by (service_name, operation)(rate(calls_total{service_name=~\"$serviceNames\"}[$__rate_interval])))",
     "legendFormat": "{{service_name}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name, operation) (rate(latency_bucket{service_name=~\"$serviceNames\"}[$__rate_interval])))",
     "legendFormat": "{{service_name}}: {{operation}}"
    }
   ]
  }
 ]
}